---
title: "Network analysis part 2"
author: "Nir Shchori & Avital Glazer"
date: "9 במאי 2016"
output: word_document
---

```{r setup, include=FALSE}
library(igraph)
library(twitteR)

consumer_key <- "o0IEnA0IVQcwq5M5DMAAcxEag"
consumer_secret <- "HnrtuzZDG7w6HcZPkIN34QdoatMVcjJr9ZOR9THtuVzSH4qblf"
access_token <- "2749462364-zjitovYLn4l0yk5QSWjVPt3JSlDdx60nBjKxzf1"
access_secret <- "CzGP68o5vyyCuv9O5z8EmVcTQqn7qTlxVYIfqRSKBBdMb"
options(httr_oauth_cache=T) #This will enable the use of a local file to cache OAuth access credentials between R sessions.
setup_twitter_oauth(consumer_key,
                    consumer_secret,
                    access_token,
                    access_secret)

start<-getUser("avitalg1") 


friends.object<-lookupUsers(start$getFriendIDs())
followers.object<-lookupUsers(start$getFollowerIDs())

n<-30 
friends <- sapply(friends.object[1:n],function(x) x$name)
followers <- sapply(followers.object[1:n],function(x) x$name)

relations <- merge(data.frame(User="avitalg1", Follower=friends), 
                   data.frame(User=friends,  Follower=friends), 
                   all=T)

g <- graph.data.frame(relations, directed = T)
V(g)$label <- V(g)$name
```

## Network analysis of twitter

```{r cars}
tkplot(g)

plot(g)

b=betweenness(g)
c=closeness(g)
d=degree(g)
e=evcent(g) 
#max betweenness
which.max(b)

#max closeness
which.max(c)

barplot(c)

#max degree
which.max(d)

barplot(d)

#max Eigencetor
which.max(e$vector)
# edge betweennes algoritem
fc=edge.betweenness.community(g)
plot(g,vertex.size=6,vertex.color=fc$membership+1,asp=FALSE)
sizes(fc)
#walktrap algoritem
ff=walktrap.community(g)
plot(g,vertex.size=6,vertex.color=ff$membership+1,asp=FALSE)
sizes(ff)



```




